const Head = () => (
	<>
		<title>UniCS</title>
		<meta name="description" content="Generated by create next app" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="icon" href="/logov2.svg" />
	</>
);

export default Head;
